version: '3.7'
# name: phone-spam
services:
  api-service:
    image: us-central1-docker.pkg.dev/gotham-433513/gotham-433513-dev-venue-artifact-registry/gotham-433513-venue-api-service:v1.2.36
    healthcheck:
      test: curl -f http://localhost:3000/api/v1/healthcheck || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 30s
    depends_on:
      postgres-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: ${APISERVICE_RESOURCES_LIMITS_CPUS:-2}
          memory: ${APISERVICE_RESOURCES_LIMITS_MEMORY:-4G}
        reservations:
          cpus: ${APISERVICE_RESOURCES_RESERVATIONS_CPUS:-1}
          memory: ${APISERVICE_RESOURCES_RESERVATIONS_MEMORY:-2G}
    environment:
      PORT: 3000
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: phone_spam
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: production
    restart: always
    ports:
      - 3001:3000
    networks:
      - phone-spam-network
    command: /bin/sh -c "npm run start"

  postgres-db:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: phone_spam
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    expose:
      - "5432"
    networks:
      - phone-spam-network

networks:
  phone-spam-network:
    name: phone-spam-network
    driver: bridge
